### ISSUE TITLE
Plugin structure

### ISSUE THREAD

**Issue by afragen** [pdclark/git-plugin-updates#14]
It might be easier to use a folder structure like the following.

```
git-plugin-updates.php
README.md
CHANGES.md
--classes
    class-updater.php
    class-updater-github.php
    class-updater-bitbucket.php
    class-controller.php
--resources
--includes
--languages
```

**Comment by pdclark** [comment]
**`classes` vs. `includes`**
I do personally prefer `classes` to `includes` for my PHP classes — all my other plugins have it that way. I've only recently switched because I noticed [10up was using includes for it's plugin template](https://github.com/10up/grunt-wp-plugin/tree/master/root). When I saw that, I wondered why... then I noticed that it's the naming convention WordPress uses for its PHP libraries — `/wp-includes` and `/wp-admin/includes`.

I think `classes` is _way_ more meaningful, but I'd rather be consistent with the WP convention.

In your example, you list both classes and includes — I'm not sure how they're different.

`languages` — Yes please. I HATE it when plugin devs don't move languages out of root. The 10up template shows a great example of how to do this.

`resources` — too generic, and I don't see WordPress using the term anywhere. 10up uses `assets`... I'd follow that if I had to pick something arbitrary, but I think `js` and `css` (in root or `includes`) is much more meaningful, and it's what WordPress does.

**Comment by pdclark** [comment]
I also typically like to use `views` or `templates` for HTML that's displayed.

**Comment by afragen** [comment]
`classes` and `includes` are very similar. It's just a way to move the `classes` into their own structure.

I've used `resources` when I've added another project into a my project. As an example, when I added https://github.com/claviska/jquery-minicolors to `afragen/events-calendar-category-colors` I put it in `resources`. I guess I'd think of it as code that's not mine.

I also use `views` or `templates` I just didn't think there were any here -- yet.

**Comment by pdclark** [comment]
Cool. I think we're very much on the same page. In the past, I've put "external" code in folders within `includes`, but I'm pretty indifferent as to whether they're there on in a root folder — as long as they're _somewhere_ unique, I'm a happy camper. :)
