### ISSUE TITLE
Change post-install move and activate, to just changing source mid-install

### ISSUE THREAD

**Issue by GaryJones** [pdclark/git-plugin-updates#8]
Compare https://github.com/brainstormmedia/git-plugin-updates/blob/master/includes/class-controller.php#L349

to

https://github.com/afragen/github-updater/blob/develop/classes/class-plugin-updater.php#L373

The latter intercepts the update install, and renames the source appropriately, adds some additional feedback, before letting WP carry on with the rest of the install. The former seems to approach this after the install has done, to then do a rename, manually activate the plugin again, and then gives some standard feedback (which should be left to WP).

As the latter is a lighter approach, can it be considered?

**Comment by pdclark** [comment]
I like the brevity of jkudish's approach (I think that method was originally his), but now that you've explained yours, it does make a lot more sense to use that earlier hook. There's also obvious higher value in providing user feedback whenever possible, so that's a major win.

Is there anything Github-specific about this, or am I reading correctly that it just takes the repository name from the plugin? (So, whether it's Github or Bitbucket, as long as it provides a repo name, it'll work fine, right?)

**Comment by pdclark** [comment]
Also, glad to see you're on UK time, because it's late in Alaska!!

**Comment by afragen** [comment]
It's repo name dependent so it shouldn't matter how the actual source names the download. As long as the repo name is contained in the downloaded file name the file rename should be correct.

**Comment by GaryJones** [comment]
> am I reading correctly that it just takes the repository name from the plugin?

Yes - it's just a filter within the update procedure - nothing GitHub-specific about it.
